/* This file was generated by syncqt with the info from sync.profile. */
#ifndef QT_EXTSERIALPORT_VERSION_H
#define QT_EXTSERIALPORT_VERSION_H

#define EXTSERIALPORT_VERSION_STR "1.9.80"

#define EXTSERIALPORT_VERSION 0x010950

#endif // QT_EXTSERIALPORT_VERSION_H
