/* This file was generated by syncqt with the info from sync.profile. */
#ifndef QT_QTEXTSERIALPORT_VERSION_H
#define QT_QTEXTSERIALPORT_VERSION_H

#define QTEXTSERIALPORT_VERSION_STR "2.0.0"

#define QTEXTSERIALPORT_VERSION 0x020000

#endif // QT_QTEXTSERIALPORT_VERSION_H
